In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


# IRIS 데이터 분류

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

In [ ]:
!wget https://raw.githubusercontent.com/dhrim/opensw_camp_2020/master/material/deep_learning/iris.csv

--2020-06-22 05:09:01--  https://raw.githubusercontent.com/dhrim/opensw_camp_2020/master/material/deep_learning/iris.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2720 (2.7K) [text/plain]
Saving to: ‘iris.csv’

iris.csv            100%[===================>]   2.66K  --.-KB/s    in 0s      

2020-06-22 05:09:01 (37.3 MB/s) - ‘iris.csv’ saved [2720/2720]



In [ ]:
!ls -al
!head iris.csv

total 20
drwxr-xr-x 1 root root 4096 Jun 22 05:09 .
drwxr-xr-x 1 root root 4096 Jun 22 05:05 ..
drwxr-xr-x 1 root root 4096 Jun 17 16:18 .config
-rw-r--r-- 1 root root 2720 Jun 22 05:09 iris.csv
drwxr-xr-x 1 root root 4096 Jun 17 16:18 sample_data
septal_length,septal_width,petal_length,petal_width,setosa,versicolor,virginica
6.4,2.8,5.6,2.2,0,0,1
5.0,2.3,3.3,1.0,0,1,0
4.9,2.5,4.5,1.7,0,0,1
4.9,3.1,1.5,0.1,1,0,0
5.7,3.8,1.7,0.3,1,0,0
4.4,3.2,1.3,0.2,1,0,0
5.4,3.4,1.5,0.4,1,0,0
6.9,3.1,5.1,2.3,0,0,1
6.7,3.1,4.4,1.4,0,1,0


In [ ]:
iris = pd.read_csv("iris.csv")
iris.head()

septal_length  septal_width  petal_length  ...  setosa  versicolor  virginica
0            6.4           2.8           5.6  ...       0           0          1
1            5.0           2.3           3.3  ...       0           1          0
2            4.9           2.5           4.5  ...       0           0          1
3            4.9           3.1           1.5  ...       1           0          0
4            5.7           3.8           1.7  ...       1           0          0

[5 rows x 7 columns]

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   septal_length  120 non-null    float64
 1   septal_width   120 non-null    float64
 2   petal_length   120 non-null    float64
 3   petal_width    120 non-null    float64
 4   setosa         120 non-null    int64  
 5   versicolor     120 non-null    int64  
 6   virginica      120 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 6.7 KB


In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 7)
[[6.4 2.8 5.6 2.2 0.  0.  1. ]
 [5.  2.3 3.3 1.  0.  1.  0. ]
 [4.9 2.5 4.5 1.7 0.  0.  1. ]
 [4.9 3.1 1.5 0.1 1.  0.  0. ]
 [5.7 3.8 1.7 0.3 1.  0.  0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(train_x, train_y, epochs=200, verbose=0)

In [ ]:
loss, acc = model.evaluate(test_x, test_y)

print("loss :", loss)
print("acc :", acc)


20/20 [==============================] - 0s 1ms/sample - loss: 0.0612 - acc: 1.0000
loss : 0.06120643764734268
acc : 1.0


In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9706930e-01 2.9302919e-03 4.3446335e-07]
 [3.2833036e-02 9.4043523e-01 2.6731769e-02]
 [9.9474621e-01 5.2515958e-03 2.2809691e-06]
 [1.4951557e-02 9.6313220e-01 2.1916179e-02]
 [9.9065429e-01 9.3442202e-03 1.4947350e-06]
 [9.9813652e-01 1.8633120e-03 1.3325450e-07]
 [9.9774134e-01 2.2585820e-03 1.2865887e-07]
 [9.9686497e-01 3.1347724e-03 2.6978194e-07]
 [1.8069820e-02 9.6339989e-01 1.8530309e-02]
 [9.9351329e-01 6.4854953e-03 1.3548229e-06]
 [8.8122603e-04 3.7372527e-01 6.2539351e-01]
 [8.4496764e-03 9.1537786e-01 7.6172389e-02]
 [9.9595189e-01 4.0474022e-03 6.5902634e-07]
 [1.5941281e-06 4.8109479e-03 9.9518740e-01]
 [9.8040819e-01 1.9587902e-02 3.8771045e-06]
 [5.0695003e-03 7.2197747e-01 2.7295303e-01]
 [8.2464004e-03 9.2450929e-01 6.7244329e-02]
 [9.9189514e-01 8.1019765e-03 2.8098636e-06]
 [9.9735487e-01 2.6448120e-03 4.1016887e-07]
 [3.4020383e-02 9.4648600e-01 1.9493669e-02]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]


# loss categorical_crossentropy

2가지 crossentropy 사용 방법
- categorical_crossentropy
- sparse_categorical_crossentropy

## categorical_crossentropy
y의 값이 one hot encoding인 경우
```
1,0,0
0,1,0
0,0,1
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어
```

loss 설정
```
model.compile(..., loss='categorical_crossentropy')
```


## sparse_categorical_crossentropy
y의 값이 one hot encoding인 경우
```
0
1
2
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어. 1이 아니라 클래스 수 3
```

loss 설정
```
model.compile(..., loss='sparse_categorical_crossentropy')
```


# iris_dnn with category index

아래의 코드는 iris_dnn_and_optimizer.ipynb의 코드를 기반으로 한다.


In [ ]:
!wget https://raw.githubusercontent.com/dhrim/opensw_camp_2020/master/material/deep_learning/iris_with_category_index.csv

--2020-06-22 05:30:53--  https://raw.githubusercontent.com/dhrim/opensw_camp_2020/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2218 (2.2K) [text/plain]
Saving to: ‘iris_with_category_index.csv’

iris_with_category_ 100%[===================>]   2.17K  --.-KB/s    in 0s      

2020-06-22 05:30:53 (33.1 MB/s) - ‘iris_with_category_index.csv’ saved [2218/2218]



In [ ]:
!ls -al
!head iris_with_category_index.csv

total 24
drwxr-xr-x 1 root root 4096 Jun 22 05:30 .
drwxr-xr-x 1 root root 4096 Jun 22 05:05 ..
drwxr-xr-x 1 root root 4096 Jun 17 16:18 .config
-rw-r--r-- 1 root root 2720 Jun 22 05:09 iris.csv
-rw-r--r-- 1 root root 2218 Jun 22 05:30 iris_with_category_index.csv
drwxr-xr-x 1 root root 4096 Jun 17 16:18 sample_data
septal_length,septal_width,petal_length,petal_width,class
6.4,2.8,5.6,2.2,2
5.0,2.3,3.3,1.0,1
4.9,2.5,4.5,1.7,2
4.9,3.1,1.5,0.1,0
5.7,3.8,1.7,0.3,0
4.4,3.2,1.3,0.2,0
5.4,3.4,1.5,0.4,0
6.9,3.1,5.1,2.3,2
6.7,3.1,4.4,1.4,1


In [ ]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(100, 4)
(100, 1)
(20, 4)
(20, 1)


In [ ]:
model = keras.Sequential()
model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

# model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=["accuracy"])
model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)
              


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_7 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_8 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
20/20 [==============================] - 0s 1ms/sample - loss: 0.0229 - acc: 1.0000
loss= 0.022887900471687317
acc= 1.0


In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9847358e-01 1.5264613e-03 1.2309558e-18]
 [7.6899896e-03 9.9223328e-01 7.6782053e-05]
 [9.8814082e-01 1.1859228e-02 3.4370640e-15]
 [1.6402206e-03 9.9827373e-01 8.6055989e-05]
 [9.9785244e-01 2.1475977e-03 3.0429613e-18]
 [9.9957103e-01 4.2895161e-04 8.7289074e-21]
 [9.9973327e-01 2.6671527e-04 1.4658062e-21]
 [9.9970859e-01 2.9136118e-04 6.2663188e-21]
 [5.1919767e-03 9.9479300e-01 1.5110068e-05]
 [9.9737012e-01 2.6298296e-03 1.1271147e-17]
 [2.6161895e-05 2.0415072e-01 7.9582316e-01]
 [9.0278673e-04 9.9801528e-01 1.0819935e-03]
 [9.9703276e-01 2.9672212e-03 7.2630362e-18]
 [7.2711309e-06 9.3889140e-02 9.0610355e-01]
 [9.9664199e-01 3.3580558e-03 1.3639418e-17]
 [5.3521415e-04 9.2279166e-01 7.6673135e-02]
 [1.1347209e-03 9.9852920e-01 3.3598760e-04]
 [9.9723262e-01 2.7673352e-03 5.8874805e-17]
 [9.9887568e-01 1.1243655e-03 7.4928465e-19]
 [2.6791799e-03 9.9724102e-01 7.9823789e-05]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]
