In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


# loss categorical_crossentropy

2가지 crossentropy 사용 방법
- categorical_crossentropy
- sparse_categorical_crossentropy

## categorical_crossentropy
y의 값이 one hot encoding인 경우
```
1,0,0
0,1,0
0,0,1
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어
```

loss 설정
```
model.compile(..., loss='categorical_crossentropy')
```


## sparse_categorical_crossentropy
y의 값이 one hot encoding인 경우
```
0
1
2
```

출력 레이어 설정
```
model.add(Dense(3, activation="softmax")) # 출력 레이어. 1이 아니라 클래스 수 3
```

loss 설정
```
model.compile(..., loss='sparse_categorical_crossentropy')
```





# iris_dnn with category index

아래의 코드는 iris_dnn_and_optimizer.ipynb의 코드를 기반으로 한다.


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense

In [ ]:
!wget https://raw.githubusercontent.com/dhrim/mnd_2020/master/material/deep_learning/iris_with_category_index.csv
  

--2019-08-20 06:32:01--  https://raw.githubusercontent.com/dhrim/mnd_2020/master/material/deep_learning/iris_with_category_index.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-20 06:32:02 ERROR 404: Not Found.



In [ ]:
iris = pd.read_csv("iris_with_category_index.csv")
iris.head()

septal_length  septal_width  petal_length  petal_width  class
0            6.4           2.8           5.6          2.2      2
1            5.0           2.3           3.3          1.0      1
2            4.9           2.5           4.5          1.7      2
3            4.9           3.1           1.5          0.1      0
4            5.7           3.8           1.7          0.3      0

In [ ]:
data = iris.to_numpy()
print(data.shape)
print(data[:5])

(120, 5)
[[6.4 2.8 5.6 2.2 2. ]
 [5.  2.3 3.3 1.  1. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.7 3.8 1.7 0.3 0. ]]


In [ ]:
x = data[:,:4]
y = data[:,4:]

split_index = 100

train_x, test_x = x[:split_index], x[split_index:]
train_y, test_y = y[:split_index], y[split_index:]

print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(100, 4)
(100, 1)
(20, 4)
(20, 1)


In [ ]:
model = keras.Sequential()
model.add(Dense(10, activation='relu', input_shape=(4,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation="softmax")) # 1이 아니고 클래스 수 3이다

# model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=["accuracy"])
model.compile(optimizer="SGD", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.summary()

model.fit(train_x, train_y, epochs=1000, verbose=0, batch_size=20)

loss, acc = model.evaluate(test_x, test_y)
print("loss=", loss)
print("acc=", acc)
              


W0820 06:32:03.460990 140052395091840 deprecation.py:506] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
20/20 [==============================] - 0s 837us/sample - loss: 0.0214 - acc: 1.0000
loss= 0.021438146010041237
acc= 1.0


In [ ]:
y_ = model.predict(test_x)
print(y_)
print(np.argmax(y_, axis=1))

[[9.9852031e-01 1.4797428e-03 5.1192541e-18]
 [7.0765279e-03 9.9287218e-01 5.1375839e-05]
 [9.9544662e-01 4.5534009e-03 4.5583586e-15]
 [1.1258841e-03 9.9883169e-01 4.2373773e-05]
 [9.9864608e-01 1.3539664e-03 3.3316072e-18]
 [9.9923372e-01 7.6633011e-04 8.5398430e-20]
 [9.9942976e-01 5.7025102e-04 1.2532759e-20]
 [9.9922740e-01 7.7260670e-04 6.4259655e-20]
 [5.2849413e-03 9.9470347e-01 1.1575490e-05]
 [9.9829751e-01 1.7025206e-03 1.2686986e-17]
 [8.8271065e-07 2.5487581e-01 7.4512327e-01]
 [4.2208584e-04 9.9892813e-01 6.4965949e-04]
 [9.9840719e-01 1.5928466e-03 8.7439046e-18]
 [4.0538857e-09 6.9718666e-02 9.3028134e-01]
 [9.9842334e-01 1.5766977e-03 8.6992972e-18]
 [6.0283339e-05 9.7464514e-01 2.5294587e-02]
 [5.2124751e-04 9.9930561e-01 1.7308856e-04]
 [9.9745816e-01 2.5418969e-03 1.2228289e-16]
 [9.9855334e-01 1.4466818e-03 3.7911325e-18]
 [2.7737301e-03 9.9717486e-01 5.1371000e-05]]
[0 1 0 1 0 0 0 0 1 0 2 1 0 2 0 1 1 0 0 1]
